name: build-and-push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out
    
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build and push Docker image
        with:
          image: ${{ github.repository }}
          registry: docker.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
